'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Shoreline_Date_Field() As String
            Get
                Return CType(Me("Shoreline_Date_Field"),String)
            End Get
            Set
                Me("Shoreline_Date_Field") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property Spacing() As Double
            Get
                Return CType(Me("Spacing"),Double)
            End Get
            Set
                Me("Spacing") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20000")>  _
        Public Property Search_Distance() As Double
            Get
                Return CType(Me("Search_Distance"),Double)
            End Get
            Set
                Me("Search_Distance") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2500")>  _
        Public Property Transect_Leg_Length() As Double
            Get
                Return CType(Me("Transect_Leg_Length"),Double)
            End Get
            Set
                Me("Transect_Leg_Length") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Baseline_Feature_Layer() As String
            Get
                Return CType(Me("Baseline_Feature_Layer"),String)
            End Get
            Set
                Me("Baseline_Feature_Layer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Shoreline_Feature_Layer() As String
            Get
                Return CType(Me("Shoreline_Feature_Layer"),String)
            End Get
            Set
                Me("Shoreline_Feature_Layer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Shoreline_Uncertainty_Field() As String
            Get
                Return CType(Me("Shoreline_Uncertainty_Field"),String)
            End Get
            Set
                Me("Shoreline_Uncertainty_Field") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("90")>  _
        Public Property Confidence_Interval() As Double
            Get
                Return CType(Me("Confidence_Interval"),Double)
            End Get
            Set
                Me("Confidence_Interval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Seaward() As Boolean
            Get
                Return CType(Me("Seaward"),Boolean)
            End Get
            Set
                Me("Seaward") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Land_On_Right_Side() As Boolean
            Get
                Return CType(Me("Land_On_Right_Side"),Boolean)
            End Get
            Set
                Me("Land_On_Right_Side") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property Uncertainty() As Double
            Get
                Return CType(Me("Uncertainty"),Double)
            End Get
            Set
                Me("Uncertainty") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property Trace_Level() As Integer
            Get
                Return CType(Me("Trace_Level"),Integer)
            End Get
            Set
                Me("Trace_Level") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Baseline_Group_Field() As String
            Get
                Return CType(Me("Baseline_Group_Field"),String)
            End Get
            Set
                Me("Baseline_Group_Field") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Intersect_Threshold_Enforced() As Boolean
            Get
                Return CType(Me("Intersect_Threshold_Enforced"),Boolean)
            End Get
            Set
                Me("Intersect_Threshold_Enforced") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Intersect_Threshold_Value() As Integer
            Get
                Return CType(Me("Intersect_Threshold_Value"),Integer)
            End Get
            Set
                Me("Intersect_Threshold_Value") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DoNotShowAgainCantInstantiateMetadataSynchronizer() As Boolean
            Get
                Return CType(Me("DoNotShowAgainCantInstantiateMetadataSynchronizer"),Boolean)
            End Get
            Set
                Me("DoNotShowAgainCantInstantiateMetadataSynchronizer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Shoreline_Type_Field() As String
            Get
                Return CType(Me("Shoreline_Type_Field"),String)
            End Get
            Set
                Me("Shoreline_Type_Field") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ifApplyRateColorRamp() As Boolean
            Get
                Return CType(Me("ifApplyRateColorRamp"),Boolean)
            End Get
            Set
                Me("ifApplyRateColorRamp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Shoreline_Uncertainty_Table() As String
            Get
                Return CType(Me("Shoreline_Uncertainty_Table"),String)
            End Get
            Set
                Me("Shoreline_Uncertainty_Table") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property search_distance_field() As String
            Get
                Return CType(Me("search_distance_field"),String)
            End Get
            Set
                Me("search_distance_field") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property Forecast_Time_Period() As Integer
            Get
                Return CType(Me("Forecast_Time_Period"),Integer)
            End Get
            Set
                Me("Forecast_Time_Period") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\")>  _
        Public Property SummaryReportLocation() As String
            Get
                Return CType(Me("SummaryReportLocation"),String)
            End Get
            Set
                Me("SummaryReportLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CreateSummaryReport() As Boolean
            Get
                Return CType(Me("CreateSummaryReport"),Boolean)
            End Get
            Set
                Me("CreateSummaryReport") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ID")>  _
        Public Property Baseline_ID_Field() As String
            Get
                Return CType(Me("Baseline_ID_Field"),String)
            End Get
            Set
                Me("Baseline_ID_Field") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ClipTransectsToShorelineExtent() As Boolean
            Get
                Return CType(Me("ClipTransectsToShorelineExtent"),Boolean)
            End Get
            Set
                Me("ClipTransectsToShorelineExtent") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DoNotShowAgainForecastCaveat() As Boolean
            Get
                Return CType(Me("DoNotShowAgainForecastCaveat"),Boolean)
            End Get
            Set
                Me("DoNotShowAgainForecastCaveat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BOTH")>  _
        Public Property CastDirection() As String
            Get
                Return CType(Me("CastDirection"),String)
            End Get
            Set
                Me("CastDirection") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.DSASAddin.My.MySettings
            Get
                Return Global.DSASAddin.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
